<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SliceForge.Core\SliceForge.Core.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>SliceForge.AspNetCore</PackageId>
    <Description>ASP.NET Core mapping from SliceForge results to HTTP results.</Description>
    <PackageTags>sliceforge;aspnetcore;results;http</PackageTags>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

</Project>
